version: '3.7'

services:
  ssr-react-boilerplate:
    container_name: ssr-react-boilerplate
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
