# pull official base image
FROM node:18.13.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./app/package.json ./
COPY ./app/package-lock.json ./

RUN apk add --update python3 make g++\
   && rm -rf /var/cache/apk/*

RUN npm install

COPY ./app/ ./
